name: Build & Deploy docs

on: [push, pull_request]

env:
  rust-toolchain: nightly-2025-01-18

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ env.rust-toolchain }}
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: x86_64
    - name: Build docs
      continue-on-error: ${{ github.ref != env.default-branch && github.event_name != 'pull_request' }}
      run: make doc_check_missing
    - name: Deploy to Github Pages
      if: ${{ github.ref == env.default-branch }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: true
        branch: gh-pages
        folder: target/doc
